
    const seed={students:[{id:'s1',name:'Aarav Sharma',email:'aarav@example.com',course:'Computer Science',cgpa:8.6,year:2026,status:'Not placed'},{id:'s2',name:'Meera Patel',email:'meera@example.com',course:'Information Technology',cgpa:9.1,year:2026,status:'Placed'},{id:'s3',name:'Rohan Kumar',email:'rohan@example.com',course:'Electronics',cgpa:7.8,year:2026,status:'Not placed'}],companies:[{id:'c1',name:'Acme Technologies',industry:'Software',email:'careers@acme.example',phone:'+91 98765 43210'},{id:'c2',name:'Northstar Analytics',industry:'Data & analytics',email:'jobs@northstar.example',phone:'+91 98765 12345'}],drives:[{id:'d1',companyId:'c1',role:'Software Engineer',package:'₹12 LPA',date:futureDate(12),minCgpa:7.5},{id:'d2',companyId:'c2',role:'Junior Data Analyst',package:'₹8 LPA',date:futureDate(25),minCgpa:7}],applications:[{id:'a1',studentId:'s1',driveId:'d1',date:today(),status:'Applied'},{id:'a2',studentId:'s2',driveId:'d1',date:today(),status:'Selected'}]};
    function futureDate(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}function today(){return new Date().toISOString().slice(0,10)}
    let db;try{db=JSON.parse(localStorage.getItem('campusPlacementData'))||structuredClone(seed)}catch{db=structuredClone(seed)}
    const save=()=>localStorage.setItem('campusPlacementData',JSON.stringify(db));const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const company=id=>db.companies.find(x=>x.id===id);const student=id=>db.students.find(x=>x.id===id);const drive=id=>db.drives.find(x=>x.id===id);const empty=(n)=>`<tr><td class="empty" colspan="${n}">No records yet. Use the button above to add one.</td></tr>`;const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';
    function render(){const upcoming=db.drives.filter(x=>x.date>=today()).sort((a,b)=>a.date.localeCompare(b.date));$('#stats').innerHTML=[['Students',db.students.length],['Companies',db.companies.length],['Upcoming drives',upcoming.length],['Placed students',db.students.filter(x=>x.status==='Placed').length]].map(([k,v])=>`<div class="card"><div class="card-label">${k}</div><div class="card-value">${v}</div></div>`).join('');$('#upcomingRows').innerHTML=upcoming.length?upcoming.slice(0,5).map(x=>`<tr><td>${esc(company(x.companyId)?.name||'Company removed')}</td><td>${esc(x.role)}</td><td>${esc(x.package)}</td><td>${fmt(x.date)}</td><td>${esc(x.minCgpa)} CGPA</td></tr>`).join(''):empty(5);
      const q=($('#studentSearch')?.value||'').toLowerCase(),sf=$('#studentFilter')?.value||'';const filtered=db.students.filter(x=>(!sf||x.status===sf)&&`${x.name} ${x.email} ${x.course}`.toLowerCase().includes(q));$('#studentRows').innerHTML=filtered.length?filtered.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.course)}</td><td>${esc(x.cgpa)}</td><td>${esc(x.year)}</td><td><span class="pill ${x.status==='Placed'?'placed':''}">${esc(x.status)}</span></td><td><button class="danger" data-delete="students:${x.id}">Delete</button></td></tr>`).join(''):empty(7);
      $('#companyRows').innerHTML=db.companies.length?db.companies.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.industry)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td><button class="danger" data-delete="companies:${x.id}">Delete</button></td></tr>`).join(''):empty(5);
      $('#driveRows').innerHTML=db.drives.length?db.drives.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<tr><td>${esc(company(x.companyId)?.name||'Company removed')}</td><td>${esc(x.role)}</td><td>${esc(x.package)}</td><td>${fmt(x.date)}</td><td>${esc(x.minCgpa)}</td><td><button class="danger" data-delete="drives:${x.id}">Delete</button></td></tr>`).join(''):empty(6);
      const af=$('#applicationFilter')?.value||'',apps=db.applications.filter(x=>!af||x.status===af);$('#applicationRows').innerHTML=apps.length?apps.map(x=>{let d=drive(x.driveId);return `<tr><td>${esc(student(x.studentId)?.name||'Student removed')}</td><td>${esc(company(d?.companyId)?.name||'Company removed')}</td><td>${esc(d?.role||'Drive removed')}</td><td>${fmt(x.date)}</td><td><select aria-label="Update application status" data-status="${x.id}">${['Applied','Shortlisted','Selected','Rejected'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="danger" data-delete="applications:${x.id}">Delete</button></td></tr>`}).join(''):empty(6)}
    function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id));render()}
    document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));['studentSearch','studentFilter','applicationFilter'].forEach(id=>$('#'+id).addEventListener('input',render));
    const specs={students:{title:'Add student',fields:[['name','Full name','text',true],['email','Email','email',true],['course','Course / department','text',true],['cgpa','CGPA (0–10)','number',true,'0.1'],['year','Graduation year','number',true,'1']]},companies:{title:'Add company',fields:[['name','Company name','text',true],['industry','Industry','text',true],['email','Contact email','email',true],['phone','Phone','tel',false]]},drives:{title:'Add placement drive',fields:[['companyId','Company','select',true],['role','Job role','text',true],['package','Package (for example ₹8 LPA)','text',true],['date','Drive date','date',true],['minCgpa','Minimum CGPA','number',true,'0.1']]},applications:{title:'Add application',fields:[['studentId','Student','select',true],['driveId','Placement drive','select',true],['status','Status','select',true]]}};let currentType='';
    function openForm(type){currentType=type;const spec=specs[type];$('#formTitle').textContent=spec.title;$('#formFields').innerHTML=spec.fields.map(([key,label,input,required,step])=>{let options=input==='select'?(key==='companyId'?db.companies.map(x=>[x.id,x.name]):key==='studentId'?db.students.map(x=>[x.id,x.name]):key==='driveId'?db.drives.map(x=>{const c=company(x.companyId);return[x.id,`${c?.name||'Company'} — ${x.role} (${fmt(x.date)})`]}):['Applied','Shortlisted','Selected','Rejected'].map(x=>[x,x])):null;let control=input==='select'?`<select name="${key}" required>${options?.length?options.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join(''):'<option value="">Add the related record first</option>'}</select>`:`<input name="${key}" type="${input}" ${required?'required':''} ${step?`step="${step}"`:''} ${key==='cgpa'||key==='minCgpa'?'min="0" max="10"':''} ${key==='year'?'min="2000" max="2100"':''}>`;return `<label class="field ${key==='package'?'full':''}">${label}${control}</label>`}).join('');$('#formDialog').showModal()}
    $('#addStudent').onclick=()=>openForm('students');$('#addCompany').onclick=()=>openForm('companies');$('#addDrive').onclick=()=>openForm('drives');$('#addApplication').onclick=()=>openForm('applications');$('#closeDialog').onclick=$('#cancelDialog').onclick=()=>$('#formDialog').close();
    $('#recordForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const id=crypto.randomUUID();if(currentType==='students'){data.cgpa=Number(data.cgpa);data.year=Number(data.year);data.status='Not placed'}if(currentType==='drives')data.minCgpa=Number(data.minCgpa);if(currentType==='applications'){data.date=today();if(data.status==='Selected'){const s=student(data.studentId);if(s)s.status='Placed'}}db[currentType].push({id,...data});save();e.currentTarget.reset();$('#formDialog').close();render()};
    document.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;const [type,id]=b.dataset.delete.split(':');const labels={students:'student',companies:'company',drives:'drive',applications:'application'};if(!confirm(`Delete this ${labels[type]}?`))return;db[type]=db[type].filter(x=>x.id!==id);save();render()});document.addEventListener('change',e=>{if(!e.target.matches('[data-status]'))return;const app=db.applications.find(x=>x.id===e.target.dataset.status);if(app){app.status=e.target.value;if(app.status==='Selected'){const s=student(app.studentId);if(s)s.status='Placed'}save();render()}});render();
  
